const constants = {
	FETCH_USER: 'FETCH_USER',
	FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
	FETCH_USER_FAILED: 'FETCH_USER_FAILED',
	FILTER_USER_BY_GENDER: 'FILTER_USER_BY_GENDER',
}
export default constants